name: CI

on:
  release:
    types: [created, published]
  push:

jobs:

  build_release_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      #- name: Install Rust stable
      #  run: |
      #    rustup toolchain update --no-self-update stable
      #    rustup default stable
      #- name: Build Gleam
      #  run: |
      #    cargo build --release
      #    target\\release\\gleam --version
      - id: create_archive
        run: |
          $ARCHIVE="gleam-$TAG_NAME-windows.zip"
          $ARCHIVE
          Compress-Archive CHANGELOG.md -DestinationPath $ARCHIVE
          echo "::set-output name=ASSET::$ARCHIVE"
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.create_archive.outputs.ASSET }}
          asset_name: ${{ steps.create_archive.outputs.ASSET }}
          asset_content_type: application/gzip